# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('bedroom_count', models.IntegerField()),
                ('livingroom_count', models.IntegerField()),
                ('house_area', models.FloatField()),
                ('house_name', models.TextField()),
                ('updated_date', models.DateField()),
                ('address', models.TextField()),
                ('district', models.TextField()),
                ('city', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.FloatField()),
                ('source', models.TextField()),
            ],
        ),
    ]
