# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserent',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='bedroom_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='district',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='house_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='livingroom_count',
            field=models.IntegerField(null=True),
        ),
    ]
