# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170113_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('bedroom_count', models.IntegerField(blank=True, null=True)),
                ('livingroom_count', models.IntegerField(blank=True, null=True)),
                ('kitchen_count', models.IntegerField(blank=True, null=True)),
                ('wc_count', models.IntegerField(blank=True, null=True)),
                ('house_area', models.FloatField(blank=True, null=True)),
                ('house_name', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('per_price', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='houserent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='bedroom_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='house_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='house_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='livingroom_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
